import {Window} from 'happy-dom';import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');const sdk=fs.readFileSync(new URL('../vendor/supabase.js',import.meta.url),'utf8');const feed=JSON.parse(fs.readFileSync(new URL('../data/results.json',import.meta.url)));
const legacy=JSON.parse(fs.readFileSync(new URL('./fixtures/legacy.json',import.meta.url)))[0].data;
const accounts={'matthew@example.test':'Matthew','tanner@example.test':'Tanner','debora@example.test':'Debora','tom@example.test':'Tom'};let storage={},writes=[],otp=0;
const user=email=>({id:'00000000-0000-0000-0000-000000000001',email,aud:'authenticated',role:'authenticated',app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:new Date().toISOString()});
const jwt=email=>[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:user(email).id,email,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'fake-signature'].join('.');
const wait=async test=>{for(let i=0;i<100;i++){if(test())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out');};
async function open(email){const hash=email?'#access_token='+jwt(email)+'&refresh_token=fake-refresh&expires_in=3600&token_type=bearer&type=magiclink':'';const w=new Window({url:'https://mbishop95-ship-it.github.io/sunday-picks/'+hash,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});for(const [k,v]of Object.entries(storage))w.localStorage.setItem(k,v);w.alert=msg=>{throw Error(msg)};w.structuredClone=structuredClone;
 w.fetch=async(url,opts={})=>{url=String(url);let data={},e='';try{e=JSON.parse(Buffer.from((new Headers(opts.headers).get('authorization')||'').split('.')[1],'base64url')).email;}catch{}if(url.includes('/data/results.json'))data=feed;else if(url.includes('/otp')){otp++;data={};}else if(url.includes('/user'))data=user(e);else if(url.includes('/sp_player'))data=accounts[e]||null;else if(url.includes('/sp_schedule'))data=feed.schedule.map(r=>({id:r.race_id,info:r}));else if(url.includes('/sp_snapshot'))data={...structuredClone(legacy),revision:1};else if(url.includes('/sp_save_pick'))writes.push(JSON.parse(opts.body));return new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});};
 w.document.body.innerHTML=html.match(/<body>([\s\S]*?)<script src=/)[1];w.eval(sdk);w.eval(html.match(/<script>([\s\S]*?)<\/script>/)[1]);await wait(()=>w.document.getElementById('saveStatus').textContent==='Shared league connected');return w;}
const close=async w=>{storage={};for(let i=0;i<w.localStorage.length;i++){let k=w.localStorage.key(i);storage[k]=w.localStorage.getItem(k);}await w.happyDOM.abort();w.close();};
let w=await open();for(const p of Object.values(accounts)){const expected=legacy.base[p]+legacy.races.filter(r=>r.scored).reduce((n,r)=>n+(r.results?.[p]?.points||0),0);const row=[...w.document.querySelectorAll('.stand')].find(row=>row.querySelector('b').textContent===p);assert.equal(Number(row.querySelector('.pts').textContent),expected);}assert.equal(w.document.querySelectorAll('[data-player]').length,0);assert.equal(w.document.getElementById('saveRace').disabled,true);w.document.getElementById('email').value='tanner@example.test';await w.document.getElementById('loginForm').onsubmit({preventDefault(){}});assert.equal(otp,1);await close(w);
w=await open('tanner@example.test');await wait(()=>w.document.getElementById('authStatus').textContent==='Signed in as Tanner');assert.equal(w.document.querySelectorAll('[data-player]').length,1);assert.equal(w.document.querySelector('[data-player]').dataset.player,'Tanner');w.document.getElementById('raceSelect').value='2026-36';w.document.getElementById('raceSelect').onchange();w.document.querySelector('[data-player]').value='Alex Bowman';await w.document.getElementById('saveRace').onclick();assert.deepEqual(writes[0],{race:'2026-36',chosen_driver:'Alex Bowman'});assert.match(w.document.getElementById('raceSelectStatus').textContent,/Eastern/);w.document.getElementById('raceSelect').value='2026-01';w.document.getElementById('raceSelect').onchange();assert.equal(w.document.getElementById('saveRace').disabled,true);assert.match(w.document.getElementById('raceSelectStatus').textContent,/Picks locked/);await close(w);
w=await open();await wait(()=>w.document.getElementById('authStatus').textContent==='Signed in as Tanner');await w.document.getElementById('signOut').onclick();await wait(()=>!w.document.getElementById('loginForm').classList.contains('hidden'));await close(w);
for(const [email,name] of Object.entries(accounts)){w=await open(email);await wait(()=>w.document.getElementById('authStatus').textContent.startsWith('Signed in as '+name));assert.equal(w.document.querySelectorAll('[data-player]').length,name==='Matthew'?4:1);assert.equal(w.document.getElementById('chaseBtn').classList.contains('hidden'),name!=='Matthew');await close(w);storage={};}
w=await open('stranger@example.com');await wait(()=>w.document.getElementById('authStatus').textContent.includes('not registered'));assert.equal(w.document.querySelectorAll('[data-player]').length,0);await close(w);
console.log('PASS: simulated DOM and real Supabase SDK, mocked HTTP: magic-link request/callback, persisted session, sign-out, all four mappings, own-pick payload, commissioner visibility, unregistered email');
